[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_02/blob/master/T02_CC-DJ-Data_Preparation_Categorical_Encoding_Challenge.ipynb)

## Categorical Encodidng

In this challenge, we will touch on another data preparation task that you should be aware of. This task revolves around dealing with "Categorical" variables. As you already know by now, Machine Learning models are based on mathematical equations. If the underlying data set contains categorical data, then the categorical variables needed to be converted into numbers since a mathematical equation only contains numbers. 

The data set used in Coding Challenge #1 contains 2 categorical variables i.e. 'Cities in Bay Area' and 'Own Home?'. The first categorical variable contains 3 categories i.e. 'Pleasanton', 'Walnut Creek' and 'Dublin' and the second categorical variable contains 2 categories i.e. 'Yes' and 'No.

Ask? Encode the 'Cities in Bay Area' categorical variable into numbers.

*Hint*: Utilize the LabelEncoder class from the sklearn.preprocessing page

*Additional Resource*: http://pbpython.com/categorical-encoding.html

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv('https://www.dropbox.com/s/ldbp498ukkdy3fd/Data-CodeChallenge2.csv?raw=1')

data_series_obj = pd.Series([])
data_series_obj = dataset.iloc[:,0:3].values
print(data_series_obj)

labelencoder = LabelEncoder()
data_series_obj[:,0] = labelencoder.fit_transform(data_series_obj[:,0])
print(data_series_obj)

[['Pleasanton' 44 172000]
 ['Walnut Creek' 27 148000]
 ['Dublin' 30 154000]
 ['Walnut Creek' 38 161000]
 ['Dublin' 40 161000]
 ['Pleasanton' 35 158000]
 ['Walnut Creek' 38 152000]
 ['Pleasanton' 48 179000]
 ['Dublin' 50 183000]
 ['Pleasanton' 37 167000]]
[[1 44 172000]
 [2 27 148000]
 [0 30 154000]
 [2 38 161000]
 [0 40 161000]
 [1 35 158000]
 [2 38 152000]
 [1 48 179000]
 [0 50 183000]
 [1 37 167000]]


## Stretch goal
`LabelEncoding` suggests a value difference between different classes. Instead, explore `OneHotEncoder` [OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) to produce categorical labels that are not biased:


In [3]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(categorical_features=[0])
data_series = onehotencoder.fit_transform(data_series_obj).toarray()

#np.set_printoptions(formatter={'float_kind':'{:00f}'.format})
#np.set_printoptions(suppress=True)
np.set_printoptions(precision=6)
print(data_series)

[[0.00e+00 1.00e+00 0.00e+00 4.40e+01 1.72e+05]
 [0.00e+00 0.00e+00 1.00e+00 2.70e+01 1.48e+05]
 [1.00e+00 0.00e+00 0.00e+00 3.00e+01 1.54e+05]
 [0.00e+00 0.00e+00 1.00e+00 3.80e+01 1.61e+05]
 [1.00e+00 0.00e+00 0.00e+00 4.00e+01 1.61e+05]
 [0.00e+00 1.00e+00 0.00e+00 3.50e+01 1.58e+05]
 [0.00e+00 0.00e+00 1.00e+00 3.80e+01 1.52e+05]
 [0.00e+00 1.00e+00 0.00e+00 4.80e+01 1.79e+05]
 [1.00e+00 0.00e+00 0.00e+00 5.00e+01 1.83e+05]
 [0.00e+00 1.00e+00 0.00e+00 3.70e+01 1.67e+05]]


In [19]:
df = dataset
pd.get_dummies(df, columns=["Cities in East Bay"]).head()

#sample.housing.map(dict(yes=1, no=0))
df.iloc[:,3] = df.iloc[:,3].map(dict(Yes=1, No=0))

dum_pd = pd.get_dummies(df, columns=["Cities in East Bay"], prefix=["City"])

print(df)
dum_pd


  Cities in East Bay  Age  Salary  Own Home?
0         Pleasanton   44  172000          0
1       Walnut Creek   27  148000          1
2             Dublin   30  154000          0
3       Walnut Creek   38  161000          0
4             Dublin   40  161000          1
5         Pleasanton   35  158000          1
6       Walnut Creek   38  152000          0
7         Pleasanton   48  179000          1
8             Dublin   50  183000          0
9         Pleasanton   37  167000          1


Age  Salary  Own Home?  City_Dublin  City_Pleasanton  City_Walnut Creek
0   44  172000          0            0                1                  0
1   27  148000          1            0                0                  1
2   30  154000          0            1                0                  0
3   38  161000          0            0                0                  1
4   40  161000          1            1                0                  0
5   35  158000          1            0                1                  0
6   38  152000          0            0                0                  1
7   48  179000          1            0                1                  0
8   50  183000          0            1                0                  0
9   37  167000          1            0                1                  0