[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_02/blob/master/T02_CCS-Solution_of_Data_Preparation_Categorical_Encoding_Challenge.ipynb)

## Categorical Encodidng

In this challenge, we will touch on another data preparation task that you should be aware of. This task revolves around dealing with "Categorical" variables. As you already know by now, Machine Learning models are based on mathematical equations. If the underlying data set contains categorical data, then the categorical variables needed to be converted into numbers since a mathematical equation only contains numbers. 

The data set used in Coding Challenge #1 contains 2 categorical variables i.e. 'Cities in Bay Area' and 'Own Home?'. The first categorical variable contains 3 categories i.e. 'Pleasanton', 'Walnut Creek' and 'Dublin' and the second categorical variable contains 2 categories i.e. 'Yes' and 'No.

Ask? Encode the 'Cities in Bay Area' categorical variable into numbers.

*Hint*: Utilize the LabelEncoder class from the sklearn.preprocessing page

*Additional Resource*: http://pbpython.com/categorical-encoding.html

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

result = pd.read_csv('https://www.dropbox.com/s/ldbp498ukkdy3fd/Data-CodeChallenge2.csv?raw=1')
new_series_obj = pd.Series([])
new_series_obj = result.iloc[:,0:3].values


print(new_series_obj)

labelencoder = LabelEncoder()
new_series_obj[:,0] = labelencoder.fit_transform(new_series_obj[:,0])

print(new_series_obj)



[['Pleasanton' 44 172000]
 ['Walnut Creek' 27 148000]
 ['Dublin' 30 154000]
 ['Walnut Creek' 38 161000]
 ['Dublin' 40 161000]
 ['Pleasanton' 35 158000]
 ['Walnut Creek' 38 152000]
 ['Pleasanton' 48 179000]
 ['Dublin' 50 183000]
 ['Pleasanton' 37 167000]]
[[1 44 172000]
 [2 27 148000]
 [0 30 154000]
 [2 38 161000]
 [0 40 161000]
 [1 35 158000]
 [2 38 152000]
 [1 48 179000]
 [0 50 183000]
 [1 37 167000]]


## Stretch goal
`LabelEncoding` suggests a value difference between different classes. Instead, explore `OneHotEncoder` [OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) to produce categorical labels that are not biased:


In [15]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(categorical_features = [0])
new_series = onehotencoder.fit_transform(new_series_obj).toarray()

#np.set_printoptions(formatter={'float_kind':'{:f}'.format})
np.set_printoptions(precision=1)
np.round(new_series,1)

print(new_series)


[[0.0e+00 1.0e+00 0.0e+00 4.4e+01 1.7e+05]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 1.5e+05]
 [1.0e+00 0.0e+00 0.0e+00 3.0e+01 1.5e+05]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 1.6e+05]
 [1.0e+00 0.0e+00 0.0e+00 4.0e+01 1.6e+05]
 [0.0e+00 1.0e+00 0.0e+00 3.5e+01 1.6e+05]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 1.5e+05]
 [0.0e+00 1.0e+00 0.0e+00 4.8e+01 1.8e+05]
 [1.0e+00 0.0e+00 0.0e+00 5.0e+01 1.8e+05]
 [0.0e+00 1.0e+00 0.0e+00 3.7e+01 1.7e+05]]


In [16]:
df = result

pd.get_dummies(df, columns=["Cities in East Bay"]).head() # make columns for different categories in specified column

dum_pd = pd.get_dummies(df, columns=["Cities in East Bay"], prefix=["City"])

dum_pd

Age  Salary Own Home?  City_Dublin  City_Pleasanton  City_Walnut Creek
0   44  172000        No            0                1                  0
1   27  148000       Yes            0                0                  1
2   30  154000        No            1                0                  0
3   38  161000        No            0                0                  1
4   40  161000       Yes            1                0                  0
5   35  158000       Yes            0                1                  0
6   38  152000        No            0                0                  1
7   48  179000       Yes            0                1                  0
8   50  183000        No            1                0                  0
9   37  167000       Yes            0                1                  0

In [22]:
lb_make = LabelEncoder()
dum_pd["Own Home?"] = lb_make.fit_transform(dum_pd["Own Home?"])
print(dum_pd)


   Age  Salary  Own Home?  City_Dublin  City_Pleasanton  City_Walnut Creek
0   44  172000          0            0                1                  0
1   27  148000          1            0                0                  1
2   30  154000          0            1                0                  0
3   38  161000          0            0                0                  1
4   40  161000          1            1                0                  0
5   35  158000          1            0                1                  0
6   38  152000          0            0                0                  1
7   48  179000          1            0                1                  0
8   50  183000          0            1                0                  0
9   37  167000          1            0                1                  0
